import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { Theme } from '@radix-ui/themes'
import { NextIntlClientProvider, hasLocale } from 'next-intl'
import { notFound } from 'next/navigation'
import { routing } from '@/i18n/routing'
import { HeaderVisibilityProvider } from '@/components/Header/HeaderVisibilityContext'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: Promise<{ locale: string }>
}) {
  const { locale } = await params
  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  return (
    <html lang={locale} className={poppins.variable} dir={locale == 'ar' ? 'rtl' : 'ltr'}>
      <body>
        <NextIntlClientProvider>
          <Theme>
            <HeaderVisibilityProvider>
              <div className="main-wrapper ">{children}</div>
            </HeaderVisibilityProvider>
          </Theme>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
