import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'
import { Theme } from '@radix-ui/themes'
import { NextIntlClientProvider, hasLocale } from 'next-intl'
import { notFound } from 'next/navigation'
import { routing } from '@/i18n/routing'
import { HeaderVisibilityProvider } from '@/components/Header/HeaderVisibilityContext'

import SmoothScrollProvider from '@/components/SmoothScrollProvider'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins'
})

const kanunAR = localFont({
  src: [
    {
      path: '../../fonts/KanunAR-Regular.otf',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../../fonts/KanunAR-Medium.otf',
      weight: '500',
      style: 'medium'
    },
    {
      path: '../../fonts/KanunAR-Bold.otf',
      weight: '700',
      style: 'bold'
    }
  ],
  variable: '--font-kanun-ar'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: Promise<{ locale: string }>
}) {
  const { locale } = await params
  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  const isArabic = locale === 'ar'
  const fontClass = isArabic ? kanunAR.variable : poppins.variable

  return (
    <html lang={locale} className={fontClass} dir={locale == 'ar' ? 'rtl' : 'ltr'}>
      <body>
        <NextIntlClientProvider>
          <Theme>
            <HeaderVisibilityProvider>
              <SmoothScrollProvider>
                <div className="main-wrapper ">{children}</div>
              </SmoothScrollProvider>
            </HeaderVisibilityProvider>
          </Theme>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
